### ISSUE TITLE
Mode shares uncalibrated for 10pct scenario v6.0

### ISSUE THREAD

**Issue by LucasJavaudin** [matsim-scenarios/matsim-berlin#120]
I am running the 10pct scenario of version 6.0, without any change to the configuration or the input files. When looking at the selected plans of the last iteration (file `berlin-v6.0.output_plans.xml.gz`), I find the following mode shares:

- walk: 68 %
- ride: 20 %
- car: 5 %
- PT: 4 %
- bike: 3 %

These mode shares are very different from the one in the paper. Is there something wrong is my run? Is version 6.0 not ready yet?

I am now running the 25pct scenario. Am I to expect the same results?

Note: I am running the simulation on a server with the following command: `java -jar matsim-berlin-6.0-pre.jar run --10pct`.

Thanks.

**Comment by rakow** [comment]
We are currently preparing the official v6.0 release. However, the mode shares were correctly calibrated in the pre-release as well. 

It should normally look similar to this: https://simwrapper.github.io/site/public/de/berlin/berlin-v6.0/output/berlin-v6.0-1pct

We will upload the calibrated 10pct plans during the next two weeks as well. Probably you should give it another try with the official release and we can see then if the issue is still there.

**Comment by rakow** [comment]
Calibrated plans for v6.0 are now available. If you want you can try again to see if the issue persists https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v6.0/

**Comment by LucasJavaudin** [comment]
Thank you. Do I need to run with branch `main` or branch `0.6.0`?

**Comment by rakow** [comment]
They are the same now. Better use main, as 6.0 might be deleted soon. You could also use the v6.0 tag

**Comment by rakow** [comment]
I assume you refer to the original paper for the Open Berlin scenario. This one was using very old survey data from 2008. 
The new model is calibrated against 2018 trip data. Please note that this is pre-corona and newer data is not available yet. When newer survey data is available, we will most likely update the calibration again.

The shares should be roughly consistent with these reported here: 
https://www.berlin.de/sen/uvk/mobilitaet-und-verkehr/verkehrsdaten/zahlen-und-fakten/mobilitaet-in-staedten-srv-2018/

There might be small differences because of how trips have been filtered, but that should not be larger than 1-2 percent points.

Also, please note that this is only the modal share for Berlin inhabitants. If you want to compare this, you will also need to filter persons living in Berlin (person id starts with berlin). The generated trip dashboards already takes this into account.
