### ISSUE TITLE
Clarifications on public transport

### ISSUE THREAD

**Issue by r-barnes** [matsim-scenarios/matsim-berlin#20]
This project is an awesome resource - thanks for working on it!

If I understand correctly, agents in the model board buses. These buses attempt to adhere to a fixed schedule drawn from, e.g., GTFS data; however, since the buses are subject to traffic congestion, they may end up running ahead of or behind schedule. Is this so?

Do agents boarding buses cause delays? That is, if 20 agents board a bus at a particular stop, does this take ~20x longer than a single agent boarding the bus? (Thus potentially causing delays?)

**Comment by ikaddoura** [comment]
Thanks! :-)

Yes, in general, this is what MATSim is capable to simulate. However, whether transit vehicles are actually delayed or not also depends on how the model is set up and how the schedule is defined.

In the berlin model, buses operate on a separate network and can't be stuck in car traffic congestion. I know it's not true, but one could say the model assumes that there are bus lanes everywhere.
(This was the easiest approach using https://github.com/matsim-org/GTFS2MATSim. However, one could also do a manual map matching of relevant bus routes or use some other GTFS -> MATSim converters at https://github.com/matsim-org which may provide some map matching features...)

Regarding the second source for delayed transit vehicles: Yes, depending on the boarding and alighting time which is defined per vehicle type (I think it's 1 sec per passenger), a large number of boarding and alighting passengers my increase the time a bus or train spends at the transit stop. If the schedule doesn't account (correctly) for longer stop times during peak demand times, transit vehicles may be delayed. See e.g. this simulation study for a simple corridor: https://www.ingentaconnect.com/content/lse/jtep/2015/00000049/00000002/art00003#

Until version 5.4 we had some problems with public transit vehicles that were delayed or ahead their schedule because of wrongly specified travel speeds (trains/buses were too fast or too slow). This issue was, hopefully, fixed in the current development version 5.5.x.

**Comment by r-barnes** [comment]
Is there any plan to map-match the buses in this scenario? The group I'm
working with is interested in finding a synthetic dataset for developing
and demonstrating bus arrival time prediction models and this simulation
seems otherwise ideal.

**Comment by ikaddoura** [comment]
No not really. We always considered this as a nice-to-have feature, but not as must-have. Sorry.

If you have the resources to work on that, we are happy to integrate the map-matched transit schedule into the project.
